sudo: false

language: php

php:
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

cache:
    directories:
        - node_modules
        - $HOME/.composer/cache/files

before_install:
    - rm -rf "$HOME/.nvm"
    - git clone https://github.com/creationix/nvm.git "$HOME/.nvm"
    - source "$HOME/.nvm/nvm.sh"
    - nvm install node
    - npm config set progress false
    - npm install -g npm
    - composer self-update

install:
    - npm install
    - composer install --prefer-source

script:
    - npm run-script lint-ci
    - composer test-ci

notifications:
    email: false

    slack:
        on_pull_requests: false
        on_start: never
        on_success: never
        on_failure: change
        rooms:
            - secure: Cpy1vg3i6q7HVnTEDKkoSjh0RxOSjVjZVlvs/XtvL/1+Kk7RC0lV6gKpLXnvP4X7qzfoIPigYvrfPdXt7DZmfJXubM+D+6lPPFIKcBBcWmGc8SBtOIaGAh0UB4KPQEF+uASpH8+dkjcGIo91byN034/4raHt64il33TyL3u8x0z2UTSAMcXbwxr2rZDf2SHyb3r3WfqgorhT3tnkDnvo/SmYrfFYf+WflL66iZGNj9XWJCRaFO6MKjsZTR0T+CnDeXNUs+Vx0vkz2CgkIn9XfxkTvSE7D5D59h5KuX5yREkJzi1x11t9xRLyPtzdRiVQ96+lTvbCgi3pIs9N4DyqU33NcJWlM+MsrvFXf1uf7589vSMxTh23GiPVRsZZKce/078z+F5kvwq61/trY/8lgAeqczD7p1npb5Z3RTOX5yMZrSfdRbI9yFYepM9V1vaAUWpNFqcC73Fcyv/E+us1+uyObfsEvqUoeN2oeulFRb61n7nrLAflOIir5xOzpCSRl91r1F4S3Dlt7Uft0XaglYdgh/hgkho2iWCyaAL1gw/EUBdUdNj/ygF/BxvVFvsTmGk7wUMJhdRf8tWGHJADOJl6JRW0h8LBHcONQEK7vTyeVpNUiMkSazVZjujZg6HBPUkxlepSXAgtdG5vNtbXd7kPYUsB2NevdZiarOqnuXQ=
